### ISSUE TITLE
Multisession Capability

### ISSUE THREAD

**Issue by aretana** [Yingzhen-ietf/BGP-QUIC#2]
Please review before updating the draft.

===

Multisession Capability (MSC)

The MSC is simply a set of flags (one octet?).  It is used to indicate that a
speaker supports multiple sessions.  If both peers have not advertised the 
capability, then it cannot be used [rfc5492].

MSC applies only when QUIC is used.  It MUST be ignored otherwise.

If more than one instance of the MSC is received, they SHOULD be ignored.  The
exception is if all the MSCs are identical (contain the same Flags).

Using the MSC allows peers to establish multiple BGP sessions, one per QUIC
stream.  Each BGP session has a separate OPEN message.  The operation of BGP
[rfc4271] remains unchanged, per session.  [Follow up on details.]

All the OPEN messages exchanged MUST include the MSC.  If one of the additional
stream-based sessions doesn't include the MSC, then it MUST be closed with a
NOTIFICATION (TBD).

When first establishing the QUIC connection, if both peers include the MSC, then a 
session per-stream MUST be used: streams cannot be used to interleave/multiplex 
data from a singe session.  If information is received on an uninitialized stream (no 
OPEN has been exchanged) then it SHOULD be ignored, unless the U + C Flags are 
set (see below)...which basically indicates today's behavior.

Flags:

All Flags described below MUST be ignored in a stream OPEN.

C = Complete Information

   When set, it indicates that all the supported AFI/SAFIs have been signaled in
   the main OPEN message.  As a result, a new AFI/SAFI cannot be signaled using
   a Stream OPEN.  If it is, then the stream session MUST be closed
   (NOTIFICATION TBD).

   If not set, then a Stream OPEN can signal additional supported AFI/SAFIs.  If
   an AFI/SAFI has already been negotiated in an active stream session, then the
   new OPEN MUST result in a NOTIFICATION (TBD).

   MUST be ignored if used in a Stream OPEN.
  

U = Use Main Stream

   When set, the Main Stream (?) is used for the signaled AFI/SAFIs (in the Main
   OPEN).  If the C Flag is also set, then no other streams are used for a new
   session -- this behavior is equivalent to not exchanging the MSC.

   If not set, then a new Stream Session SHOULD be opened before any UPDATES are
   exchanged.

   MUST be ignored if used in a Stream OPEN.

M = Maintenance

   When set, it indicates that sessions are maintained from a single set of
   events: the HoldTimer for all sessions is reset when a KEEPALIVE or UPDATE
   message is received [rfc4271], on any stream session.  One one stream session
   is REQUIRED to send KEEPALIVES, but they MAY be send on any or all stream
   sessions.

   If not set, then each stream session has an independent HoldTimer.

   All other BGP Timers (Section 10/rfc4271) are maintained per session.  Using
   this Flag is RECOMMENDED.

   Each Stream Session can use a different HoldTimer, either resulting from
   configuration or the Hold Time value in the OPEN message.

**Comment by Yingzhen-ietf** [comment]
I was thinking to only define one AFI/SAFI one stream mode. So there are two operational mode in your proposal:

1. When U is set, there is a main stream (need to figure out a better name) for control messages. It’s responsible for keepalive and hold timer for all sessions. One question here, it’s ok to send keepalives in this stream for all sessions, however since each stream operates independently, it does not know when an UPDATE message is received in a session, so a requirement need to be added: if an UPDATE message is received in a session, it MUST notify the main stream to reset the hold timer.

"All the OPEN messages exchanged MUST include the MSC. "
"MUST be ignored if used in a Stream OPEN.”.
I’m a bit confused by these two sentences. Here do you mean these flags are ignored in a stream for one AFI/SAFI? Not the main/control stream?

2. No main stream. Each stream has its own keepalive and hold timer. 

Thanks,
Yingzhen

**Comment by aretana** [comment]
> I was thinking to only define one AFI/SAFI one stream mode. So there are two
> operational mode in your proposal:
> 
> 1. When U is set, there is a main stream (need to figure out a better name)
> for control messages. It’s responsible for keepalive and hold timer for all
> sessions. One question here, it’s ok to send keepalives in this stream for all
> sessions, however since each stream operates independently, it does not know
> when an UPDATE message is received in a session, so a requirement need to be
> added: if an UPDATE message is received in a session, it MUST notify the main
> stream to reset the hold timer.

U means that the Main Stream will be used for whatever AFI/SAFIs were signaled.  Each stream is independent wrt maintenance.

M means that there's a single timer for all streams -- regardless of which session the KEEPALIVEs or UPDATES are received.  No need to add extra text, it's an implementation detail. ;-)


> "All the OPEN messages exchanged MUST include the MSC. "
> "MUST be ignored if used in a Stream OPEN.”.
> I’m a bit confused by these two sentences. Here do you mean these flags are
> ignored in a stream for one AFI/SAFI? Not the main/control stream?

Right, the C/U flags only make sense in the Main Stream.

> 2. No main stream. Each stream has its own keepalive and hold timer.

The Main Stream is the original session (first OPEN).  But each stream can have independent timers if the M Flag is not set.

I am now thinking that we don't need the M Flag.  Instead:

- There's a single HoldTimer.

- If the operator wants a session to have a lower/higher Hold Time, then the OPEN negotiation will basically be the signal to start a separate timer for that session/stream.

**Comment by aretana** [comment]
If we only have 2 Flags (C/U), and the other variable is whether the multi-protocol capability (MP below) includes the same list of AFI/SAFIs.  So I made a table:

       Peer A     Peer B
      C     U     C    U    MP    Action
          
1     0     0     0    0    No    NOTIFICATION

2     0     0     0    0    Yes   Established + Open a stream

3     0     0     0    1    No    NOTIFICATION

4     0     0     0    1    Yes   Established + Use Main stream
                                  + Open other Streams (if needed)

5     0     0     1    0    No    NOTIFICATION

6     0     0     1    0    Yes   Established + Open a stream

7     0     0     1    1    No    NOTIFICATION

8     0     0     1    1    Yes   Established + Use Main stream (*)

9     0     1     0    0    No    = 3 (NOTIFICATION)

10    0     1     0    0    Yes   = 4 (Established + Use Main stream
                                  + Open other Streams (if needed))

11    0     1     0    1    No    NOTIFICATION

12    0     1     0    1    Yes   = 4 (Established + Use Main stream
                                  + Open other Streams (if needed))

13    0     1     1    0    No    NOTIFICATION

14    0     1     1    0    Yes   Established + Use Main stream (*)

15    0     1     1    1    No    NOTIFICATION

16    0     1     1    1    Yes   Established + Use Main stream (*)

17    1     0     0    0    No    = 5 (NOTIFICATION)

18    1     0     0    0    Yes   = 6 (Established + Open a stream)

19    1     0     0    1    No    NOTIFICATION

20    1     0     0    1    Yes   Established + Use Main stream (*)

21    1     0     1    0    No    NOTIFICATION

22    1     0     1    0    Yes   Established + Open a stream

23    1     0     1    1    No    NOTIFICATION

24    1     0     1    1    Yes   Established + Use Main stream (*)

25    1     1     0    0    No    = 7 (NOTIFICATION)

26    1     1     0    0    Yes   = 8 (Established + Use Main stream (*))

27    1     1     0    1    No    NOTIFICATION

28    1     1     0    1    Yes   Established + Use Main stream (*)

29    1     1     1    0    No    NOTIFICATION

30    1     1     1    0    Yes   Established + Use Main stream (*)

31    1     1     1    1    No    NOTIFICATION

32    1     1     1    1    Yes   Established + Use Main stream (*)


Conclusions:

- The MP capability MUST be the same, always.  No change from today.

- If both C and U are set (in any combination: by one peer, or both), then the session will only have the Main Stream.  This is the same as I-D.chen-idr-bgp-over-quic.

- If U is not set, then the Main Stream won't be used to exchange UPDATES; a new Stream Session MUST be opened first.

**Comment by Yingzhen-ietf** [comment]
Hi, 

Somehow I think the C/U flag over complicates things.

Basically there are two operational mode:
1. Draft-chen-idr-bgp-over-quic, there may be multiple streams, the details to be defined in the draft (what’s already out there is not enough).
2. Per AFI/SAFI per stream, this is indicated by including MSC capability in the OPEN message.

You can’t mix these two modes, so U flag is not really necessary.

About C flag, this means the first OPEN message is sent for all later sessions need to include all supported AFI/SAFIs. A configuration normally starts from basic AFI/SAFIs, say IPv4 unicast, then add other AFI/SAFIs later. Plus, since there is an OPEN message for each stream, it includes the MSC and MP capability anyway. Let’s discuss more about this flag.

One hold timer for all sessions, the problem I see here is that if for some reason, one session/stream got stuck, it won’t get reset since the holder timer is for the entire QUIC connection, and you won’t be able to create a new stream since there is already a stuck one for the AFI/SAFI.  So I’d suggest each stream keeps it’s own hold timer.

 Am I missing anything? Thoughts?

Thanks,
Yingzhen

**Comment by aretana** [comment]
Yes, you're right -- I'm overthinking this.


If the MSC is not advertised, or if only one peer advertises it, then we fall back to draft-chen-idr-bgp-over-quic.

If both peers advertise the MSC, then a session is set up for whatever AFI/SAFIs are negotiated.  All sessions (not just the first one) MUST include the MSC.


About the timers -- I was trying to translate what we wrote in the patent about a "control session".  I see your point about a session being stuck...
